# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libunwind

# >> macros
# << macros
%define keepstatic 1

Summary:    A library to determine the call-chain of a program
Version:    1.1
Release:    1
Group:      Development/Libraries
License:    expat
URL:        http://www.nongnu.org/libunwind/
Source0:    libunwind-%{version}.tar.bz2
Source100:  libunwind.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)

%description
The primary goal of this project is to define a portable and efficient C
programming interface (API) to determine the call-chain of a program.
The API additionally provides the means to manipulate the preserved
(callee-saved) state of each call-frame and to resume execution at any
point in the call-chain (non-local goto). The API supports both local
(same-process) and remote (across-process) operation. As such, the API
is useful in a number of applications.


%package devel
Summary:    libunwind development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for libunwind


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
export CFLAGS="-U_FORTIFY_SOURCE"
# << build pre

%reconfigure 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/lib*so*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}
%{_libdir}/lib*.a
%{_mandir}/man3
%{_libdir}/pkgconfig/libunwind-coredump.pc
%{_libdir}/pkgconfig/libunwind-generic.pc
%{_libdir}/pkgconfig/libunwind-ptrace.pc
%{_libdir}/pkgconfig/libunwind-setjmp.pc
%{_libdir}/pkgconfig/libunwind.pc
# >> files devel
# << files devel
